INSERT INTO firmy (nazwa_firmy, opis_firmy)
VALUES ('PPUT Ostrans', 'Prywatne Przedsiębiorstwo Usług Transportowych Ostrans'),
('MZK Ostrołęka', 'Miejskie Zakłady Komunikacyjne w Ostrołęce'),
('DPO', 'Dopravní podnik Ostrava a.s.'),
('PMDP', 'Plzeňské městské dopravní podniky'),
('Osmuni', 'Ostromunikacja'),
('Kujatrans', 'Kujawsko-Pomorskie Przedsiębiorstwo Transportowe'),
('PKM Gliwice', 'Przedsiębiorstwo Komunikacji Miejskiej w Gliwicach'),
('Transgór', 'Przedsiębiorstwo Transportowe Transgór'),
('Kłosok', 'Przedsiębiorstwo Transportowe Kłosok'),
('PKM Tychy', 'Przedsiębiorstwo Komunikacji Miejskiej w Tychach'),
('PKM Katowice', 'Przedsiębiorstwo Komunikacji Miejskiej w Katowicach'),
('MZK Jaworzno', 'Miejskie Zakłady Komunikacyjne w Jaworznie'),
('MZK Bydgoszcz', 'Miejskie Zakłady Komunikacyjne w Bydgoszczy'),
('MZK Toruń', 'Miejskie Zakłady Komunikacyjne w Toruniu'),
('MZK Lublin', 'Miejskie Zakłady Komunikacyjne w Lublinie'),
('MPK Szczecin', 'Miejskie Przedsiębiorstwo Komunikacyjne w Szczecinie'),
('MPK Kraków', 'Miejskie Przedsiębiorstwo Komunikacyjne w Krakowie'),
('MPK Wrocław', 'Miejskie Przedsiębiorstwo Komunikacyjne we Wrocławiu'),
('ZTM Warszawa', 'Zarząd Transportu Miejskiego w Warszawie'),
('ZTM Gdańsk', 'Zarząd Transportu Miejskiego w Gdańsku'),
('ZTM Poznań', 'Zarząd Transportu Miejskiego w Poznaniu')
('GAiT', 'Gdańskie Autobusy i Tramwaje'),
('Solaris','Solaris Bus & Coach sp. z o.o.'),
('MAN','MAN Truck & Bus sp. z o.o.'),
('Mercedes-Benz','Daimler Buses Polska Sp. z o.o.'),
('SOR','SOR Libchavy spol. s r. o.'),
('Volvo','AB Volvo'),
('Škoda','ŠKODA TRANSPORTATION a.s.'),
('MPK Włocławek', 'Miejskie Przedsiębiorstwo Komunikacyjne we Włocławku'),
('MPK Słupsk', 'Miejskie Przedsiębiorstwo Komunikacyjne w Słupsku'),
('MPK Bielsko-Biała', 'Miejskie Przedsiębiorstwo Komunikacyjne w Bielsku-Białej'),
('MPK Wałbrzych', 'Miejskie Przedsiębiorstwo Komunikacyjne w Wałbrzychu'),
('MPK Opoczno', 'Miejskie Przedsiębiorstwo Komunikacyjne w Opocznie'),
('MPK Jaworzno', 'Miejskie Przedsiębiorstwo Komunikacyjne w Jaworznie'),
('MPK Tarnów', 'Miejskie Przedsiębiorstwo Komunikacyjne w Tarnowie'),
('MPK Koszalin', 'Miejskie Przedsiębiorstwo Komunikacyjne w Koszalinie'),
('MPK Zielona Góra', 'Miejskie Przedsiębiorstwo Komunikacyjne w Zielonej Górze'),
('MPK Opole', 'Miejskie Przedsiębiorstwo Komunikacyjne w Opolu'),
('MPK Gdynia', 'Miejskie Przedsiębiorstwo Komunikacyjne w Gdyni'),
('MPK Poznań', 'Miejskie Przedsiębiorstwo Komunikacyjne w Poznaniu'),
('MPK Bydgoszcz', 'Miejskie Przedsiębiorstwo Komunikacyjne w Bydgoszczy'),
('MPK Lublin', 'Miejskie Przedsiębiorstwo Komunikacyjne w Lublinie'),
('MPK Rzeszów', 'Miejskie Przedsiębiorstwo Komunikacyjne w Rzeszowie'),
('MPK Łódź', 'Miejskie Przedsiębiorstwo Komunikacyjne w Łodzi'),
('MPK Częstochowa', 'Miejskie Przedsiębiorstwo Komunikacyjne w Częstochowie'),
('PKS Gdańsk', 'Przedsiębiorstwo Komunikacji Samochodowej w Gdańsku'),
('PKS Słupsk', 'Przedsiębiorstwo Komunikacji Samochodowej w Słupsku'),
('PKS Koszalin', 'Przedsiębiorstwo Komunikacji Samochodowej w Koszalinie'),
('PKS Elbląg', 'Przedsiębiorstwo Komunikacji Samochodowej w Elblągu'),
('PKS Olsztyn', 'Przedsiębiorstwo Komunikacji Samochodowej w Olsztynie'),
('PKS Białystok', 'Przedsiębiorstwo Komunikacji Samochodowej w Białymstoku'),
('PKS Lublin', 'Przedsiębiorstwo Komunikacji Samochodowej w Lublinie'),
('PKS Radom', 'Przedsiębiorstwo Komunikacji Samochodowej w Radomiu'),
('PKS Kielce', 'Przedsiębiorstwo Komunikacji Samochodowej w Kielcach'),
('PKS Częstochowa', 'Przedsiębiorstwo Komunikacji Samochodowej w Częstochowie'),
('PKS Katowice', 'Przedsiębiorstwo Komunikacji Samochodowej w Katowicach'),
('PKS Bielsko-Biała', 'Przedsiębiorstwo Komunikacji Samochodowej w Bielsku-Białej'),
('PKS Rzeszów', 'Przedsiębiorstwo Komunikacji Samochodowej w Rzeszowie'),
('PKS Przemyśl', 'Przedsiębiorstwo Komunikacji Samochodowej w Przemyślu'),
('PKS Tarnów', 'Przedsiębiorstwo Komunikacji Samochodowej w Tarnowie'),
('PKS Nowy Sącz', 'Przedsiębiorstwo Komunikacji Samochodowej w Nowym Sączu'),
('PKS Zakopane', 'Przedsiębiorstwo Komunikacji Samochodowej w Zakopanem');