INSERT INTO marki (nazwa_marki)
VALUES ('Solaris'),
('MAN'),
('Mercedes-Benz'),
('Isuzu'),
('Jelcz'),
('SOR'),
('Volvo'),
('Škoda'),
('Setra'),
('Neoplan'),
('Autosan'),
('Karosa'),
('Ikarus'),
('ZiU'),
('Trolza'),
('Tatra'),
('Konstal'),
('Duewag'),
('Pesa'),
('Siemens'),
('Bombardier'),
('VanHool');